### ISSUE TITLE
Ignore tags

### ISSUE THREAD

**Issue by Shatur** [milisims/nvim-luaref#10]
Could you remove `doc/tags` from the repo and add it to gitignore? This file is generated by vim when you running `:helptags` and usually plugins require to generate after installation.

**Comment by milisims** [comment]
The reason I chose to add was a note in `:h help-translated`:

> - Make a package with all the files and the tags file available for download.
>  Users can drop it in one of the "doc" directories and start use it.

This is referring specifically to translated versions of the official help files, but I felt that it made sense to include them. Additionally, I suspect after a few updates this repository will largely not change.

I'm willing to change my mind (for example, plopping the docs in a release tgz), but is there any compelling reason to? Do those regenerated tags differ from the ones generated on my machine? I'm not sure why they would

**Comment by Shatur** [comment]
If there is any change in Vim / Neovim, or you accidentally forget to update the tags in the repository, the file will change. Personally, I would suggest not to include the generated files in the repository. This is what all plugins usually do. So it's more like a suggestion.

**Comment by dhruvmanila** [comment]
[Packer.nvim](https://github.com/wbthomason/packer.nvim) fails to update the plugin with this error message:
```
 ✗ Failed to update milisims/nvim-luaref
  Errors:
    error: The following untracked working tree files would be overwritten by merge:
    	doc/tags
    Please move or remove them before you merge.
    Aborting
    Updating 2eb9dec..2044d4d
    2eb9dec
```

**Comment by milisims** [comment]
Thanks, I'll remove them.
