### ISSUE TITLE
Limit Languages

### ISSUE THREAD

**Issue by tjdevries** [milisims/nvim-luaref#8]
It'd be nice if there was a way to only have some of the languages downloaded or added to helptags -- it's not a big deal to have the extra ones, but it'd be nice if they didn't show up in my tab complete.

Cool plugin :)

**Comment by milisims** [comment]
Oops, those don't show up in fzf's `:Helptags`.
I think I'll end up just moving out the additional langs to a separate directory, and a note in the en help file and readme for how add it back in, which is somewhat in line with `:h help-translated`

Thank you!

**Comment by tjdevries** [comment]
No problem :) thanks!
